### ISSUE TITLE
Cloud Fails to Boot

### ISSUE THREAD

**Issue by NickStephens** [edurange/edurange#3]
While testing a scenario on cloud.edurange.org. I continued to get the Runtime Error 'clouds failed to boot'. I was testing the new scenario 'ROP'. I was able to boot it once successfully, after that I destroyed the scenario without unbooting it. I then tried to boot ROP once more after making changes to its YML file. I got the error 'clouds failed to boot'. I then went into the EC2 console and manually terminated the instance I forgot to unboot and released the Elastic IP addresses which were bound to the old instance. This seemed to yield no results and new ROP scenarios continually fail to boot with the same error message. Why does this happen? This seems like a bug.

**Comment by NickStephens** [comment]
Also, I should note that other scenarios with unchanged YML files also fail to boot, notably ELF.

**Comment by kahea** [comment]
Click the down arrow button next to scenario/cloud/subnet/instance and
click 'show log' it will give you the full trace of any errors. They might
of failed because we reached our vpc limit which is 5 but I can't say for
sure until I see the error trace.

**Comment by kahea** [comment]
I just test booted a scenario on cloud and we have reached our limit of
vpc's. You can log into edurange aws account and release any resources your
not using. The resources should be tagged with host being cloud and user
being nick. In the aws console you can filter resources by tags for quickly
finding them.

**Comment by NickStephens** [comment]
Thanks Kahea.

As you said the issue was that I had not released the VPC. Strongly encourage making it so destroying a scenario frees all the scenario's associated resources.
